spring.application.name=demo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://monorail.proxy.rlwy.net:49345/railway
spring.datasource.username=postgres
spring.datasource.password=gErYWIyWMwnnmINTPctMcejLDpkCaXBz
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
